### ISSUE TITLE
[Enhancement] Native support for Apple Silicon (Universal Binaries)

### ISSUE THREAD

**Issue by itslukebond** [LiveEnhancementSuite/LESforMacOS#11]
Is it possible to get a universal MacOS build of LES? I noticed the HammerSpoon app running is saying intel on my M1 system. Says on the HammerSpoon site it’s been native as of  0.9.82 - http://hammerspoon.github.io/releasenotes/0.9.82.html

thankyou!

**Comment by kwvg** [comment]
Hello! I current don't have a macOS system to work with, I've been daily driving Debian for quite a while, hence the radio silence on the LES front. I'll be sure to look into this when I have a macOS system to work with.

Hope this is resolved soon.

**Comment by itslukebond** [comment]
No problem! I had a go at building it myself in Xcode via command line but was getting certificate errors. Only recently started dipping my toes in development.

**Comment by kwvg** [comment]
All past versions of LES have been re-released. [v1.3.2](https://github.com/LiveEnhancementSuite/LESforMacOS/releases/tag/v1.3.2) and [v1.3.3](https://github.com/LiveEnhancementSuite/LESforMacOS/releases/tag/v1.3.3) are now built as Universal Binaries. Could you verify they work on your Apple Silicon Mac?

**Comment by kwvg** [comment]
Proper behavior on Apple Silicon has been confirmed through beta testers, closing!
