### ISSUE TITLE
[Bug] LESforMacOS uses same bundle ID as Hammerspoon, breaks usage

### ISSUE THREAD

**Issue by core-code** [LiveEnhancementSuite/LESforMacOS#13]
the bundle-identifier (CFBundleIdentifer) should be changed to something unique. it currently still is `org.hammerspoon.Hammerspoon` making it indistinguishable from the original Hammerspoon

**Comment by kwvg** [comment]
These changes have now made to `develop` (see https://github.com/LiveEnhancementSuite/LESforMacOS/commit/99c5d8a3e5b9a97cf7fbea8358de660a9c044c09) and LESforMacOS now occupies a distinct bundle name. These changes should be made available in v1.3.4

**Comment by core-code** [comment]
thanks!
