### ISSUE TITLE
[Bug] macOS Big Sur cannot verify that this app has no malware 

### ISSUE THREAD

**Issue by microfx** [LiveEnhancementSuite/LESforMacOS#4]
Hey!

Can't start the app – any beta I could try that is signed?

Cheers!

**Comment by Inversil** [comment]
as far as I know don't have a development signature for any builds because it costs over a hundred dollars each year; the best thing you could do is disable gatekeeper temporarily or at least give yourself the permission to allow apps run from anywhere.

**Comment by microfx** [comment]
aight... thanks for the quick response!
